language: node_js

env:
  global:
    - FORCE_POSTINSTALL=true

node_js:
  - '14'
  - '12'
  - '10'

before_install:
  - node --version
  - yarn --version

install:
  - npm install

os:
  - linux
  - osx
  - windows

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
    - os: windows

script:
  - npm test
